#!/bin/sh

# Status log

echo "Installing git packages..."

brew bundle --file=- <<EOF
  brew "git"
  brew "hub"

  cask 'github-desktop'
EOF

if app_is_installed 'GitHub'; then
  fancy_echo "It looks like you've already configured your GitHub SSH keys."
  fancy_echo "If not, you can do it by signing in to the GitHub app on your Mac."
elif [ ! -f "$HOME/.ssh/github_rsa.pub" ]; then
  open ~/Applications/GitHub\ Desktop.app
fi
