#!/bin/zsh

# Status log

echo "Installing server development packages..."

brew bundle --file=- <<EOF
  brew "python"
  brew "ansible"
  brew "go"
  brew "protobuf"

  cask "google-cloud-sdk"
EOF

if ! go list ... | grep -Fqs delve; then
  echo "Installing Delve for Go..."
  go get -u github.com/derekparker/delve/cmd/dlv
fi

go get -u github.com/golang/protobuf/{proto,protoc-gen-go}

pip2.7 install virtualenv
